-- Logbook – Supabase Schema (full snapshot, regenerated from the live DB)
-- Covers migrations 0001–0057. This file is the authoritative current state;
-- it was generated by introspecting the production database (pg_get_functiondef,
-- pg_policies, pg_constraint, information_schema) so policy and function bodies
-- are verbatim. Use it to stand up a fresh project; keep it in sync on schema
-- changes (see CLAUDE.md → "Datenbank").

-- ── Tables ────────────────────────────────────────────────────────────────────

CREATE TABLE public.zane_profiles (
  id   uuid NOT NULL,
  name text NOT NULL,
  approved boolean DEFAULT false
);

CREATE TABLE public.zane_exercises (
  id text NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  tags text[] DEFAULT '{}'::text[],
  note text NOT NULL DEFAULT ''::text,
  category text,
  unilateral boolean NOT NULL DEFAULT false,
  equipment text,
  progression_reps integer
);

CREATE TABLE public.zane_schedules (
  id text NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  days jsonb NOT NULL DEFAULT '[]'::jsonb,
  archived boolean NOT NULL DEFAULT false,
  versions jsonb NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE public.zane_sessions (
  id text NOT NULL,
  user_id uuid NOT NULL,
  schedule_id text,
  day_id text,
  day_name text,
  date timestamp with time zone,
  ended timestamp with time zone,
  entries jsonb NOT NULL DEFAULT '[]'::jsonb,
  started_at timestamp with time zone,
  duration_minutes integer,
  feel text
);

CREATE TABLE public.zane_session_entries (
  id text NOT NULL,
  session_id text NOT NULL,
  user_id uuid NOT NULL,
  entry_idx integer NOT NULL,
  ex_id text,
  name text NOT NULL DEFAULT ''::text,
  planned_sets integer,
  planned_reps integer,
  note text NOT NULL DEFAULT ''::text,
  superset_group text,
  planned_reps_per_set integer[]
);

CREATE TABLE public.zane_sets (
  id text NOT NULL,
  session_id text NOT NULL,
  entry_id text NOT NULL,
  user_id uuid NOT NULL,
  set_idx integer NOT NULL,
  kg numeric,
  reps integer,
  reps_l integer,
  reps_r integer,
  done boolean NOT NULL DEFAULT false,
  skipped boolean NOT NULL DEFAULT false,
  warmup boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.zane_cardio_logs (
  id               text        NOT NULL,
  user_id          uuid        NOT NULL,
  date             text        NOT NULL,
  type             text,
  duration_minutes integer     NOT NULL,
  distance_m       numeric,
  pace_feeling     integer     CHECK (pace_feeling BETWEEN 1 AND 6),
  effort           integer     CHECK (effort BETWEEN 1 AND 10),
  note             text,
  created_at       timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.zane_daily_logs (
  id           text        NOT NULL,
  user_id      uuid        NOT NULL,
  date         text        NOT NULL,
  weight       numeric,
  steps        integer,
  calories     integer,
  protein      integer,
  carbs        integer,
  fat          integer,
  water_ml     integer,
  note         text,
  adherence    numeric,
  targets_snap jsonb,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zane_daily_logs_user_id_date_key UNIQUE (user_id, date)
);

CREATE TABLE public.zane_skips (
  id text NOT NULL,
  user_id uuid,
  date text NOT NULL,
  day_id text,
  day_name text,
  skip_reason text,
  skipped_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.zane_user_settings (
  user_id uuid NOT NULL,
  active_schedule_id text,
  cycle_index integer NOT NULL DEFAULT 0,
  last_advanced_date date,
  unit text NOT NULL DEFAULT 'kg'::text,
  rest_default integer NOT NULL DEFAULT 120,
  in_progress_session_id text,
  cycle_start_date text,
  push_enabled boolean DEFAULT false,
  rest_big integer DEFAULT 180,
  rest_medium integer DEFAULT 120,
  rest_small integer DEFAULT 90,
  cycle_week_view boolean DEFAULT false,
  accent_color text DEFAULT 'gold'::text,
  dark_mode text DEFAULT 'dark'::text,
  pushover_user_key text,
  week_plan_start_date date,
  tempo_enabled boolean DEFAULT false,
  tempo_eccentric numeric DEFAULT 4,
  tempo_concentric numeric DEFAULT 1,
  smart_progression boolean DEFAULT false,
  progression_range_top integer DEFAULT 4,
  equipment_config jsonb,
  custom_day_types text[] NOT NULL DEFAULT '{}'::text[],
  reminder_enabled boolean NOT NULL DEFAULT false,
  reminder_time text NOT NULL DEFAULT '07:00'::text,
  next_reminder_at timestamp with time zone,
  show_warmup_in_summary boolean NOT NULL DEFAULT true,
  show_coaching_tab boolean DEFAULT false,
  be_your_own_coach boolean NOT NULL DEFAULT false,
  session_timeout_minutes integer DEFAULT 90,
  auto_close_notify jsonb,
  macro_targets jsonb,
  show_health_tab boolean NOT NULL DEFAULT false
);

CREATE TABLE public.zane_pushover_active (
  id    text NOT NULL DEFAULT 'singleton'::text,
  nonce text NOT NULL DEFAULT ''::text
);

CREATE TABLE public.zane_feature_grants (
  feature text NOT NULL,
  email   text NOT NULL
);

-- ── Coaching ──────────────────────────────────────────────────────────────────

CREATE TABLE public.zane_coaching (
  id text NOT NULL,
  coach_id uuid NOT NULL,
  client_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  checkin_requested_at timestamp with time zone,
  checkin_enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE public.zane_coaching_threads (
  id text NOT NULL,
  coaching_id text NOT NULL,
  name text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.zane_coaching_notes (
  id text NOT NULL,
  coaching_id text NOT NULL,
  author_id uuid NOT NULL,
  type text NOT NULL,
  entity_id text,
  entity_name text,
  body text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  thread_id text
);

CREATE TABLE public.zane_coaching_macros (
  id text NOT NULL,
  coaching_id text NOT NULL,
  set_by uuid NOT NULL,
  set_at timestamp with time zone NOT NULL DEFAULT now(),
  calories_training integer,
  protein_training integer,
  carbs_training integer,
  fat_training integer,
  calories_rest integer,
  protein_rest integer,
  carbs_rest integer,
  fat_rest integer
);

CREATE TABLE public.zane_checkins (
  id text NOT NULL,
  coaching_id text NOT NULL,
  client_id uuid NOT NULL,
  week_start date NOT NULL,
  checked_in_at timestamp with time zone NOT NULL DEFAULT now(),
  weight_today numeric,
  weight_avg_last_week numeric,
  off_plan_notes text,
  hydration_ml integer,
  days_trained integer,
  steps integer,
  cardio_minutes integer,
  cardio_distance_m integer,
  goal_note text,
  hunger integer,
  sleep_quality integer,
  life_stress integer,
  work_stress integer,
  tiredness integer,
  issues_notes text,
  general_note text,
  cardio_pace_feeling integer,
  cardio_effort integer,
  performance_vs_last_week text
);

-- ── Constraints (primary keys, unique, foreign keys, checks) ───────────────────

ALTER TABLE public.zane_profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_exercises ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_exercises ADD CONSTRAINT exercises_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_schedules ADD CONSTRAINT schedules_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_schedules ADD CONSTRAINT schedules_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.zane_sessions ADD CONSTRAINT zane_sessions_feel_check CHECK ((feel = ANY (ARRAY['easy'::text, 'good'::text, 'hard'::text, 'very_hard'::text, 'max'::text])));

ALTER TABLE public.zane_session_entries ADD CONSTRAINT zane_session_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_session_entries ADD CONSTRAINT zane_session_entries_session_id_entry_idx_key UNIQUE (session_id, entry_idx);
ALTER TABLE public.zane_session_entries ADD CONSTRAINT zane_session_entries_session_id_fkey FOREIGN KEY (session_id) REFERENCES zane_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.zane_session_entries ADD CONSTRAINT zane_session_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_sets ADD CONSTRAINT zane_sets_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_sets ADD CONSTRAINT zane_sets_entry_id_set_idx_key UNIQUE (entry_id, set_idx);
ALTER TABLE public.zane_sets ADD CONSTRAINT zane_sets_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES zane_session_entries(id) ON DELETE CASCADE;
ALTER TABLE public.zane_sets ADD CONSTRAINT zane_sets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_cardio_logs ADD CONSTRAINT zane_cardio_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_cardio_logs ADD CONSTRAINT zane_cardio_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_skips ADD CONSTRAINT zane_skips_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_skips ADD CONSTRAINT zane_skips_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_user_settings ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id);
ALTER TABLE public.zane_user_settings ADD CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_pushover_active ADD CONSTRAINT pushover_active_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_feature_grants ADD CONSTRAINT feature_grants_pkey PRIMARY KEY (feature, email);

ALTER TABLE public.zane_coaching ADD CONSTRAINT zane_coaching_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_coaching ADD CONSTRAINT zane_coaching_coach_id_client_id_key UNIQUE (coach_id, client_id);
ALTER TABLE public.zane_coaching ADD CONSTRAINT zane_coaching_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.zane_coaching ADD CONSTRAINT zane_coaching_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.zane_coaching ADD CONSTRAINT zane_coaching_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text])));

ALTER TABLE public.zane_coaching_threads ADD CONSTRAINT zane_coaching_threads_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_coaching_threads ADD CONSTRAINT zane_coaching_threads_coaching_id_fkey FOREIGN KEY (coaching_id) REFERENCES zane_coaching(id) ON DELETE CASCADE;
ALTER TABLE public.zane_coaching_threads ADD CONSTRAINT zane_coaching_threads_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.zane_coaching_notes ADD CONSTRAINT zane_coaching_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_coaching_notes ADD CONSTRAINT zane_coaching_notes_coaching_id_fkey FOREIGN KEY (coaching_id) REFERENCES zane_coaching(id) ON DELETE CASCADE;
ALTER TABLE public.zane_coaching_notes ADD CONSTRAINT zane_coaching_notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.zane_coaching_notes ADD CONSTRAINT zane_coaching_notes_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES zane_coaching_threads(id) ON DELETE SET NULL;
ALTER TABLE public.zane_coaching_notes ADD CONSTRAINT zane_coaching_notes_type_check CHECK ((type = ANY (ARRAY['session'::text, 'plan'::text, 'general'::text, 'change'::text])));

ALTER TABLE public.zane_coaching_macros ADD CONSTRAINT zane_coaching_macros_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_coaching_macros ADD CONSTRAINT zane_coaching_macros_coaching_id_fkey FOREIGN KEY (coaching_id) REFERENCES zane_coaching(id) ON DELETE CASCADE;

ALTER TABLE public.zane_checkins ADD CONSTRAINT zane_checkins_pkey PRIMARY KEY (id);
ALTER TABLE public.zane_checkins ADD CONSTRAINT zane_checkins_coaching_id_week_start_key UNIQUE (coaching_id, week_start);
ALTER TABLE public.zane_checkins ADD CONSTRAINT zane_checkins_coaching_id_fkey FOREIGN KEY (coaching_id) REFERENCES zane_coaching(id) ON DELETE CASCADE;
ALTER TABLE public.zane_checkins ADD CONSTRAINT zane_checkins_client_id_fkey FOREIGN KEY (client_id) REFERENCES zane_profiles(id) ON DELETE CASCADE;

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX zane_coaching_client_id_idx ON public.zane_coaching USING btree (client_id);
CREATE INDEX zane_coaching_notes_coaching_id_created_at_idx ON public.zane_coaching_notes USING btree (coaching_id, created_at DESC);
CREATE INDEX zane_coaching_notes_coaching_id_read_at_idx ON public.zane_coaching_notes USING btree (coaching_id, read_at) WHERE (read_at IS NULL);
CREATE INDEX zane_coaching_notes_thread_id_idx ON public.zane_coaching_notes USING btree (thread_id) WHERE (thread_id IS NOT NULL);
CREATE INDEX zane_coaching_threads_coaching_id_created_at_idx ON public.zane_coaching_threads USING btree (coaching_id, created_at);
CREATE INDEX zane_session_entries_session_id_idx ON public.zane_session_entries USING btree (session_id);
CREATE INDEX zane_sets_entry_id_idx ON public.zane_sets USING btree (entry_id);
CREATE INDEX zane_sets_session_id_idx ON public.zane_sets USING btree (session_id);

-- ── Row Level Security ─────────────────────────────────────────────────────────

ALTER TABLE public.zane_profiles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_exercises        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_schedules        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_sessions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_session_entries  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_sets             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_cardio_logs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_daily_logs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_skips            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_user_settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_feature_grants   ENABLE ROW LEVEL SECURITY;  -- no policies: service-role / SECURITY DEFINER only
ALTER TABLE public.zane_pushover_active  ENABLE ROW LEVEL SECURITY;  -- no policies: service-role only (pushover edge fn)
ALTER TABLE public.zane_coaching         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_coaching_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_coaching_notes   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_coaching_macros  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_checkins         ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY "own profile" ON public.zane_profiles FOR ALL TO public USING ((auth.uid() = id));
CREATE POLICY "coach can read client profile" ON public.zane_profiles FOR SELECT TO public USING (zane_is_coach_of(id));

-- exercises
CREATE POLICY "own exercises" ON public.zane_exercises FOR ALL TO public USING ((auth.uid() = user_id));
CREATE POLICY "coach can read client exercises" ON public.zane_exercises FOR SELECT TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can write client exercises" ON public.zane_exercises FOR INSERT TO public WITH CHECK (zane_is_coach_of(user_id));
CREATE POLICY "coach can update client exercises" ON public.zane_exercises FOR UPDATE TO public USING (zane_is_coach_of(user_id));

-- schedules
CREATE POLICY "own schedules" ON public.zane_schedules FOR ALL TO public USING ((auth.uid() = user_id));
CREATE POLICY "coach can read client schedules" ON public.zane_schedules FOR SELECT TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can write client schedules" ON public.zane_schedules FOR INSERT TO public WITH CHECK (zane_is_coach_of(user_id));
CREATE POLICY "coach can update client schedules" ON public.zane_schedules FOR UPDATE TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can delete client schedules" ON public.zane_schedules FOR DELETE TO public USING (zane_is_coach_of(user_id));

-- sessions
CREATE POLICY "own sessions" ON public.zane_sessions FOR ALL TO public USING ((auth.uid() = user_id));
CREATE POLICY "coach can read client sessions" ON public.zane_sessions FOR SELECT TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can write client sessions" ON public.zane_sessions FOR INSERT TO public WITH CHECK (zane_is_coach_of(user_id));
CREATE POLICY "coach can update client sessions" ON public.zane_sessions FOR UPDATE TO public USING (zane_is_coach_of(user_id));

-- session_entries
CREATE POLICY "zane_session_entries_rls" ON public.zane_session_entries FOR ALL TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "coach can read client entries" ON public.zane_session_entries FOR SELECT TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can write client entries" ON public.zane_session_entries FOR INSERT TO public WITH CHECK (zane_is_coach_of(user_id));
CREATE POLICY "coach can update client entries" ON public.zane_session_entries FOR UPDATE TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can delete client entries" ON public.zane_session_entries FOR DELETE TO public USING (zane_is_coach_of(user_id));

-- sets
CREATE POLICY "zane_sets_rls" ON public.zane_sets FOR ALL TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "coach can read client sets" ON public.zane_sets FOR SELECT TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can write client sets" ON public.zane_sets FOR INSERT TO public WITH CHECK (zane_is_coach_of(user_id));
CREATE POLICY "coach can update client sets" ON public.zane_sets FOR UPDATE TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can delete client sets" ON public.zane_sets FOR DELETE TO public USING (zane_is_coach_of(user_id));

-- cardio logs
CREATE POLICY "Users manage own cardio logs" ON public.zane_cardio_logs FOR ALL TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));

-- daily logs
CREATE POLICY "Users manage own daily logs" ON public.zane_daily_logs FOR ALL TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "coach can read client daily logs" ON public.zane_daily_logs FOR SELECT TO authenticated USING (zane_is_coach_of(user_id));

-- skips
CREATE POLICY "own skips" ON public.zane_skips FOR ALL TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "coach can read client skips" ON public.zane_skips FOR SELECT TO public USING (zane_is_coach_of(user_id));

-- user_settings
CREATE POLICY "own settings" ON public.zane_user_settings FOR ALL TO public USING ((auth.uid() = user_id));
CREATE POLICY "coach can read client settings" ON public.zane_user_settings FOR SELECT TO public USING (zane_is_coach_of(user_id));
CREATE POLICY "coach can update client settings" ON public.zane_user_settings FOR UPDATE TO public USING (zane_is_coach_of(user_id));

-- coaching
CREATE POLICY "coaching visible to participants" ON public.zane_coaching FOR SELECT TO public USING (((coach_id = auth.uid()) OR (client_id = auth.uid())));
CREATE POLICY "coach can invite" ON public.zane_coaching FOR INSERT TO public WITH CHECK ((coach_id = auth.uid()));
CREATE POLICY "client can respond to invite" ON public.zane_coaching FOR UPDATE TO public USING ((client_id = auth.uid()));
CREATE POLICY "coach can update coaching row" ON public.zane_coaching FOR UPDATE TO public USING ((coach_id = auth.uid()));
CREATE POLICY "participants can end coaching" ON public.zane_coaching FOR DELETE TO public USING (((coach_id = auth.uid()) OR (client_id = auth.uid())));

-- coaching_threads
CREATE POLICY "threads visible to participants" ON public.zane_coaching_threads FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_threads.coaching_id) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid()))))));
CREATE POLICY "participants can create threads" ON public.zane_coaching_threads FOR INSERT TO public WITH CHECK (((created_by = auth.uid()) AND (EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_threads.coaching_id) AND (c.status = 'active'::text) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid())))))));
CREATE POLICY "participants can delete threads" ON public.zane_coaching_threads FOR DELETE TO public USING ((EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_threads.coaching_id) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid()))))));

-- coaching_notes
CREATE POLICY "notes visible to participants" ON public.zane_coaching_notes FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_notes.coaching_id) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid()))))));
CREATE POLICY "participants can write notes" ON public.zane_coaching_notes FOR INSERT TO public WITH CHECK (((author_id = auth.uid()) AND (EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_notes.coaching_id) AND (c.status = 'active'::text) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid())))))));
CREATE POLICY "recipient can mark read" ON public.zane_coaching_notes FOR UPDATE TO public USING (((author_id <> auth.uid()) AND (EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_notes.coaching_id) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid())))))));
CREATE POLICY "participants can delete notes" ON public.zane_coaching_notes FOR DELETE TO public USING ((EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_coaching_notes.coaching_id) AND ((c.coach_id = auth.uid()) OR (c.client_id = auth.uid()))))));

-- coaching_macros
CREATE POLICY "Coach can manage macros" ON public.zane_coaching_macros FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM zane_coaching WHERE ((zane_coaching.id = zane_coaching_macros.coaching_id) AND (zane_coaching.coach_id = auth.uid())))));
CREATE POLICY "Client can read macros" ON public.zane_coaching_macros FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM zane_coaching WHERE ((zane_coaching.id = zane_coaching_macros.coaching_id) AND (zane_coaching.client_id = auth.uid())))));

-- checkins
CREATE POLICY "checkins_client" ON public.zane_checkins FOR ALL TO authenticated
  USING ((client_id = auth.uid()))
  WITH CHECK (((client_id = auth.uid()) AND (EXISTS ( SELECT 1 FROM zane_coaching c WHERE ((c.id = zane_checkins.coaching_id) AND (c.client_id = auth.uid()))))));
CREATE POLICY "checkins_coach_read" ON public.zane_checkins FOR SELECT TO authenticated
  USING ((EXISTS ( SELECT 1 FROM zane_coaching WHERE ((zane_coaching.id = zane_checkins.coaching_id) AND (zane_coaching.coach_id = auth.uid()) AND (zane_coaching.status = 'active'::text)))));

-- ── Functions (verbatim from the live database) ────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.zane_user_settings (user_id) VALUES (new.id)
  ON CONFLICT DO NOTHING;
  RETURN new;
END;
$function$;

CREATE OR REPLACE FUNCTION public.zane_is_coach_of(p_client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from zane_coaching
    where coach_id = auth.uid()
      and client_id = p_client_id
      and status = 'active'
  )
$function$;

CREATE OR REPLACE FUNCTION public.check_active_users_access()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() = 'office@btc-prime.biz' THEN
    RETURN true;
  END IF;
  RETURN EXISTS (
    SELECT 1 FROM zane_feature_grants
    WHERE feature = 'active_users' AND email = auth.email()
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_active_users_grants()
 RETURNS TABLE(email text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' THEN
    RETURN;
  END IF;
  RETURN QUERY
  SELECT fg.email FROM zane_feature_grants fg WHERE fg.feature = 'active_users' ORDER BY fg.email;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_active_users_grant(p_email text, p_granted boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  IF p_granted THEN
    INSERT INTO zane_feature_grants (feature, email)
    VALUES ('active_users', lower(trim(p_email)))
    ON CONFLICT DO NOTHING;
  ELSE
    DELETE FROM zane_feature_grants
    WHERE feature = 'active_users' AND email = lower(trim(p_email));
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_pending_users()
 RETURNS TABLE(user_id uuid, name text, email text, created_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' THEN
    RETURN;
  END IF;
  RETURN QUERY
    SELECT p.id, p.name, u.email::text, u.created_at
    FROM zane_profiles p
    JOIN auth.users u ON u.id = p.id
    WHERE p.approved = false
    ORDER BY u.created_at ASC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.approve_user(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  UPDATE zane_profiles SET approved = true WHERE id = p_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.decline_user(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM zane_profiles WHERE id = p_user_id AND approved = false) THEN
    RAISE EXCEPTION 'User not found or already approved';
  END IF;
  DELETE FROM zane_profiles WHERE id = p_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.find_user_by_email(p_email text)
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id from auth.users where lower(email) = lower(p_email) limit 1
$function$;

CREATE OR REPLACE FUNCTION public.invite_client(p_email text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_client_id uuid;
  v_id        text;
  v_existing  text;
BEGIN
  v_client_id := find_user_by_email(p_email);
  IF v_client_id IS NULL THEN
    RETURN 'ERROR:not_found';
  END IF;
  IF v_client_id = auth.uid() THEN
    RETURN 'ERROR:self';
  END IF;
  SELECT id INTO v_existing FROM zane_coaching
    WHERE coach_id = auth.uid() AND client_id = v_client_id;
  IF FOUND THEN
    RETURN 'ERROR:exists:' || v_existing;
  END IF;
  PERFORM 1 FROM zane_coaching
    WHERE client_id = v_client_id AND status = 'active';
  IF FOUND THEN
    RETURN 'ERROR:already_coached';
  END IF;
  v_id := 'cch_' || gen_random_uuid()::text;
  INSERT INTO zane_coaching (id, coach_id, client_id, status)
    VALUES (v_id, auth.uid(), v_client_id, 'pending');
  RETURN v_id;
END
$function$;

CREATE OR REPLACE FUNCTION public.respond_to_coaching_invite(p_coaching_id text, p_accept boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_accept then
    delete from zane_coaching
      where client_id = auth.uid()
        and status = 'active'
        and coach_id <> client_id
        and id <> p_coaching_id;
    update zane_coaching
      set status = 'active'
      where id = p_coaching_id and client_id = auth.uid() and status = 'pending';
    delete from zane_coaching
      where client_id = auth.uid()
        and status = 'pending'
        and id <> p_coaching_id;
  else
    delete from zane_coaching
      where id = p_coaching_id and client_id = auth.uid();
  end if;
end
$function$;

CREATE OR REPLACE FUNCTION public.enable_self_coaching()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_id       text;
  v_existing text;
begin
  select id into v_existing from zane_coaching
    where coach_id = auth.uid() and client_id = auth.uid();
  if found then
    update zane_coaching set status = 'active'
      where id = v_existing and status <> 'active';
    return v_existing;
  end if;
  v_id := 'self_' || gen_random_uuid()::text;
  insert into zane_coaching (id, coach_id, client_id, status)
    values (v_id, auth.uid(), auth.uid(), 'active');
  return v_id;
end
$function$;

CREATE OR REPLACE FUNCTION public.get_coach_info()
 RETURNS TABLE(coaching_id text, coach_id uuid, coach_email text, coach_name text, status text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select c.id, c.coach_id, u.email, coalesce(p.name, u.email), c.status
  from zane_coaching c
  join auth.users u on u.id = c.coach_id
  left join zane_profiles p on p.id = c.coach_id
  where c.client_id = auth.uid()
    and c.coach_id <> c.client_id
$function$;

CREATE OR REPLACE FUNCTION public.get_coaching_clients()
 RETURNS TABLE(coaching_id text, client_id uuid, client_email text, client_name text, status text, checkin_enabled boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT c.id, c.client_id, u.email, COALESCE(p.name, u.email), c.status, c.checkin_enabled
  FROM zane_coaching c
  JOIN auth.users u ON u.id = c.client_id
  LEFT JOIN zane_profiles p ON p.id = c.client_id
  WHERE c.coach_id = auth.uid()
    AND c.coach_id <> c.client_id
$function$;

CREATE OR REPLACE FUNCTION public.get_coach_clients_status()
 RETURNS TABLE(client_id uuid, in_progress_session_id text)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select us.user_id as client_id, us.in_progress_session_id
  from zane_user_settings us
  inner join zane_coaching zc on zc.client_id = us.user_id
  where zc.coach_id = auth.uid()
    and zc.coach_id <> zc.client_id
    and zc.status = 'active'
    and us.in_progress_session_id is not null;
$function$;

CREATE OR REPLACE FUNCTION public.get_coach_checkin_status()
 RETURNS TABLE(coaching_id text, checked_in_at timestamptz)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_week_start date;
begin
  v_week_start := current_date
    - (extract(dow from current_date)::int) * interval '1 day'
    - interval '6 days';

  return query
  select
    c.id as coaching_id,
    (
      select ci.checked_in_at from zane_checkins ci
      where ci.coaching_id = c.id
        and ci.week_start = v_week_start
      limit 1
    ) as checked_in_at
  from zane_coaching c
  where c.coach_id = auth.uid()
    and c.coach_id <> c.client_id
    and c.status = 'active';
end;
$function$;

CREATE OR REPLACE FUNCTION public.sync_sets_batch(p_sets jsonb)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  INSERT INTO zane_sets (
    id, session_id, entry_id, user_id,
    set_idx, kg, reps, reps_l, reps_r,
    done, skipped, warmup, updated_at
  )
  SELECT
    s->>'id',
    s->>'session_id',
    s->>'entry_id',
    auth.uid(),
    (s->>'set_idx')::int,
    (s->>'kg')::numeric,
    (s->>'reps')::int,
    (s->>'reps_l')::int,
    (s->>'reps_r')::int,
    COALESCE((s->>'done')::boolean,    false),
    COALESCE((s->>'skipped')::boolean, false),
    COALESCE((s->>'warmup')::boolean,  false),
    (s->>'updated_at')::timestamptz
  FROM jsonb_array_elements(p_sets) AS s
  ON CONFLICT (id) DO UPDATE SET
    kg         = EXCLUDED.kg,
    reps       = EXCLUDED.reps,
    reps_l     = EXCLUDED.reps_l,
    reps_r     = EXCLUDED.reps_r,
    done       = EXCLUDED.done,
    skipped    = EXCLUDED.skipped,
    warmup     = EXCLUDED.warmup,
    updated_at = EXCLUDED.updated_at
  WHERE zane_sets.updated_at < EXCLUDED.updated_at;
$function$;

-- Build the store-shaped (camelCase) entries array for a session from the
-- relational tables — the single source of truth since migration 0058. Used by
-- the reporting RPCs below (the legacy zane_sessions.entries JSONB is no longer
-- written by the client).
CREATE OR REPLACE FUNCTION public.zane_entries_json(p_session_id text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'exId', e.ex_id,
      'name', e.name,
      'plannedSets', e.planned_sets,
      'plannedReps', e.planned_reps,
      'plannedRepsPerSet', e.planned_reps_per_set,
      'note', e.note,
      'supersetGroup', e.superset_group,
      'sets', COALESCE((
        SELECT jsonb_agg(
          jsonb_build_object(
            'kg', st.kg, 'reps', st.reps, 'repsL', st.reps_l, 'repsR', st.reps_r,
            'done', st.done, 'skipped', st.skipped, 'warmup', st.warmup
          ) ORDER BY st.set_idx)
        FROM zane_sets st WHERE st.entry_id = e.id
      ), '[]'::jsonb)
    ) ORDER BY e.entry_idx
  ), '[]'::jsonb)
  FROM zane_session_entries e
  WHERE e.session_id = p_session_id;
$function$;

CREATE OR REPLACE FUNCTION public.get_active_sessions_overview()
 RETURNS TABLE(user_id uuid, session_id text, user_name text, day_name text, sets_done integer, sets_total integer, started_at timestamp with time zone, ended timestamp with time zone, is_finished boolean, avg_duration_seconds double precision, avg_sets_total double precision)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' AND
     NOT EXISTS (SELECT 1 FROM zane_feature_grants WHERE feature = 'active_users' AND email = auth.email())
  THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    us.user_id,
    s.id::text AS session_id,
    p.name::text AS user_name,
    s.day_name::text,
    (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = s.id AND st.done)::int AS sets_done,
    (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = s.id AND NOT st.skipped)::int AS sets_total,
    s.started_at,
    NULL::timestamptz AS ended,
    false AS is_finished,
    (
      SELECT AVG(CASE WHEN s2.duration_minutes IS NOT NULL THEN s2.duration_minutes * 60.0
                      ELSE EXTRACT(EPOCH FROM (s2.ended - s2.started_at)) END)
      FROM zane_sessions s2
      WHERE s2.user_id = us.user_id AND s2.day_id = s.day_id AND s2.ended IS NOT NULL
        AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
    )::float AS avg_duration_seconds,
    (
      SELECT AVG(sub.cnt)::float FROM (
        SELECT (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = s2.id AND st.done) AS cnt
        FROM zane_sessions s2
        WHERE s2.user_id = us.user_id AND s2.day_id = s.day_id AND s2.ended IS NOT NULL
          AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
      ) sub
    )::float AS avg_sets_total
  FROM zane_user_settings us
  JOIN zane_sessions s ON s.id = us.in_progress_session_id
  LEFT JOIN zane_profiles p ON p.id = us.user_id
  WHERE us.in_progress_session_id IS NOT NULL AND s.ended IS NULL

  UNION ALL

  SELECT
    fs.user_id,
    fs.id::text AS session_id,
    p.name::text AS user_name,
    fs.day_name::text,
    (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = fs.id AND st.done)::int AS sets_done,
    (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = fs.id AND NOT st.skipped)::int AS sets_total,
    fs.started_at,
    fs.ended,
    true AS is_finished,
    (
      SELECT AVG(CASE WHEN s2.duration_minutes IS NOT NULL THEN s2.duration_minutes * 60.0
                      ELSE EXTRACT(EPOCH FROM (s2.ended - s2.started_at)) END)
      FROM zane_sessions s2
      WHERE s2.user_id = fs.user_id AND s2.day_id = fs.day_id AND s2.ended IS NOT NULL
        AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
    )::float AS avg_duration_seconds,
    (
      SELECT AVG(sub.cnt)::float FROM (
        SELECT (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = s2.id AND st.done) AS cnt
        FROM zane_sessions s2
        WHERE s2.user_id = fs.user_id AND s2.day_id = fs.day_id AND s2.ended IS NOT NULL
          AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
      ) sub
    )::float AS avg_sets_total
  FROM (
    SELECT DISTINCT ON (s.user_id) s.*
    FROM zane_sessions s
    WHERE s.ended IS NOT NULL
      AND s.ended > NOW() - INTERVAL '24 hours'
      AND (s.duration_minutes IS NOT NULL OR (s.started_at IS NOT NULL AND s.ended > s.started_at))
    ORDER BY s.user_id, s.ended DESC
  ) fs
  LEFT JOIN zane_profiles p ON p.id = fs.user_id
  WHERE NOT EXISTS (
    SELECT 1 FROM zane_user_settings us2
    JOIN zane_sessions s2 ON s2.id = us2.in_progress_session_id
    WHERE us2.user_id = fs.user_id AND s2.ended IS NULL
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_active_session_detail(p_user_id uuid, p_session_id text DEFAULT NULL::text)
 RETURNS TABLE(user_name text, day_name text, started_at timestamp with time zone, ended timestamp with time zone, entries jsonb, avg_duration_seconds double precision, avg_sets_total double precision, last_session_entries jsonb, last_session_duration_seconds double precision, unit text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.email() IS DISTINCT FROM 'office@btc-prime.biz' AND
     NOT EXISTS (SELECT 1 FROM zane_feature_grants WHERE feature = 'active_users' AND email = auth.email()) AND
     NOT zane_is_coach_of(p_user_id)
  THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    p.name::text AS user_name,
    s.day_name::text,
    s.started_at,
    s.ended,
    zane_entries_json(s.id) AS entries,
    (
      SELECT AVG(CASE WHEN s2.duration_minutes IS NOT NULL THEN s2.duration_minutes * 60.0
                      ELSE EXTRACT(EPOCH FROM (s2.ended - s2.started_at)) END)
      FROM zane_sessions s2
      WHERE s2.user_id = p_user_id AND s2.day_id = s.day_id AND s2.ended IS NOT NULL AND s2.id != s.id
        AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
    )::float AS avg_duration_seconds,
    (
      SELECT AVG(sub.cnt)::float FROM (
        SELECT (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = s2.id AND st.done) AS cnt
        FROM zane_sessions s2
        WHERE s2.user_id = p_user_id AND s2.day_id = s.day_id AND s2.ended IS NOT NULL AND s2.id != s.id
          AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
      ) sub
    )::float AS avg_sets_total,
    zane_entries_json((
      SELECT s2.id FROM zane_sessions s2
      WHERE s2.user_id = p_user_id AND s2.day_id = s.day_id AND s2.ended IS NOT NULL AND s2.id != s.id
        AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
      ORDER BY s2.ended DESC LIMIT 1
    )) AS last_session_entries,
    (
      SELECT COALESCE(s2.duration_minutes * 60.0, EXTRACT(EPOCH FROM (s2.ended - s2.started_at)))
      FROM zane_sessions s2
      WHERE s2.user_id = p_user_id AND s2.day_id = s.day_id AND s2.ended IS NOT NULL AND s2.id != s.id
        AND (s2.duration_minutes IS NOT NULL OR (s2.started_at IS NOT NULL AND s2.ended > s2.started_at))
      ORDER BY s2.ended DESC LIMIT 1
    )::float AS last_session_duration_seconds,
    COALESCE((SELECT us.unit FROM zane_user_settings us WHERE us.user_id = p_user_id), 'kg')::text AS unit
  FROM zane_sessions s
  LEFT JOIN zane_profiles p ON p.id = s.user_id
  WHERE s.user_id = p_user_id
    AND (
      (p_session_id IS NOT NULL AND s.id = p_session_id)
      OR
      (p_session_id IS NULL AND s.ended IS NULL AND s.id = (
        SELECT us.in_progress_session_id FROM zane_user_settings us WHERE us.user_id = p_user_id
      ))
    );
END;
$function$;

-- ── Server-side history aggregation RPCs (migration 0059) ───────────────

CREATE OR REPLACE FUNCTION public.get_exercise_best_e1rm(p_user_id uuid DEFAULT NULL)
 RETURNS TABLE(ex_id text, best_e1rm double precision)
 LANGUAGE sql STABLE SECURITY INVOKER SET search_path TO 'public'
AS $function$
  WITH uid AS (SELECT COALESCE(p_user_id, auth.uid()) AS id)
  SELECT e.ex_id,
    MAX(st.kg * (1 + (
      CASE WHEN st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL
           THEN LEAST(COALESCE(st.reps_l, st.reps_r), COALESCE(st.reps_r, st.reps_l))
           ELSE st.reps END
    )::numeric / 30.0))::float AS best_e1rm
  FROM zane_session_entries e
  JOIN zane_sets st ON st.entry_id = e.id
  JOIN zane_sessions s ON s.id = e.session_id
  WHERE e.user_id = (SELECT id FROM uid)
    AND e.ex_id IS NOT NULL
    AND s.ended IS NOT NULL
    AND NOT st.warmup AND NOT st.skipped AND st.kg IS NOT NULL
    AND COALESCE(
      CASE WHEN st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL
           THEN LEAST(COALESCE(st.reps_l, st.reps_r), COALESCE(st.reps_r, st.reps_l))
           ELSE st.reps END, 0) > 0
  GROUP BY e.ex_id;
$function$;

-- Recent ended sessions that logged a given exercise, newest first, each with
-- that exercise's sets. Powers seed/progression at session start, the "last
-- time" card and the exercise-history screen without the full history client-side.
CREATE OR REPLACE FUNCTION public.get_exercise_history(p_ex_id text, p_day_id text DEFAULT NULL, p_limit int DEFAULT 12, p_user_id uuid DEFAULT NULL)
 RETURNS TABLE(session_id text, day_id text, date timestamptz, ended timestamptz, sets jsonb)
 LANGUAGE sql STABLE SECURITY INVOKER SET search_path TO 'public'
AS $function$
  WITH uid AS (SELECT COALESCE(p_user_id, auth.uid()) AS id)
  SELECT s.id AS session_id, s.day_id, s.date, s.ended,
    COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'kg', st.kg, 'reps', st.reps, 'repsL', st.reps_l, 'repsR', st.reps_r,
        'done', st.done, 'skipped', st.skipped, 'warmup', st.warmup
      ) ORDER BY st.set_idx)
      FROM zane_sets st WHERE st.entry_id = e.id
    ), '[]'::jsonb) AS sets
  FROM zane_sessions s
  JOIN zane_session_entries e ON e.session_id = s.id
  WHERE e.user_id = (SELECT id FROM uid)
    AND e.ex_id = p_ex_id
    AND s.ended IS NOT NULL
    AND (p_day_id IS NULL OR s.day_id = p_day_id)
    AND EXISTS (SELECT 1 FROM zane_sets st2 WHERE st2.entry_id = e.id
                AND (st2.kg IS NOT NULL OR st2.reps IS NOT NULL OR st2.reps_l IS NOT NULL OR st2.reps_r IS NOT NULL))
  ORDER BY s.ended DESC
  LIMIT GREATEST(p_limit, 1);
$function$;

-- All-time totals for the stats screen (volume = sum kg*effReps over completed
-- working sets; minutes; session + done-set counts). Streaks stay client-side
-- (plan-aware, need only session dates which boot still loads as metadata).
CREATE OR REPLACE FUNCTION public.get_user_volume_stats(p_user_id uuid DEFAULT NULL)
 RETURNS TABLE(session_count bigint, total_volume double precision, total_minutes bigint, total_done_sets bigint)
 LANGUAGE sql STABLE SECURITY INVOKER SET search_path TO 'public'
AS $function$
  WITH uid AS (SELECT COALESCE(p_user_id, auth.uid()) AS id),
  ended AS (
    SELECT s.id, s.duration_minutes, s.started_at, s.ended
    FROM zane_sessions s WHERE s.user_id = (SELECT id FROM uid) AND s.ended IS NOT NULL
  )
  SELECT
    (SELECT COUNT(*) FROM ended)::bigint AS session_count,
    COALESCE((
      SELECT SUM(st.kg * (
        CASE WHEN st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL
             THEN LEAST(COALESCE(st.reps_l, st.reps_r), COALESCE(st.reps_r, st.reps_l))
             ELSE st.reps END))
      FROM zane_sets st JOIN ended en ON en.id = st.session_id
      WHERE NOT st.warmup AND NOT st.skipped AND st.kg IS NOT NULL
        AND COALESCE(CASE WHEN st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL
             THEN LEAST(COALESCE(st.reps_l, st.reps_r), COALESCE(st.reps_r, st.reps_l))
             ELSE st.reps END, 0) > 0
    ), 0)::float AS total_volume,
    COALESCE((SELECT SUM(COALESCE(en.duration_minutes,
        CASE WHEN en.started_at IS NOT NULL AND en.ended > en.started_at
             THEN EXTRACT(EPOCH FROM (en.ended - en.started_at))/60 ELSE 0 END))::bigint FROM ended en), 0)::bigint AS total_minutes,
    COALESCE((SELECT COUNT(*) FROM zane_sets st JOIN ended en ON en.id = st.session_id
              WHERE st.done AND NOT st.warmup AND NOT st.skipped), 0)::bigint AS total_done_sets;
$function$;

-- Per-session aggregates for the windowed boot (migration 0060): the history
-- list / "best session" card / coach session lists need volume + set/exercise
-- counts for sessions whose sets weren't loaded. Semantics match the client's
-- totalVolume()/doneSetCount() for ended sessions (done flag not required).
CREATE OR REPLACE FUNCTION public.get_session_stats(p_user_id uuid DEFAULT NULL)
 RETURNS TABLE(session_id text, exercise_count integer, done_sets integer, volume double precision)
 LANGUAGE sql STABLE SECURITY INVOKER SET search_path TO 'public'
AS $function$
  WITH uid AS (SELECT COALESCE(p_user_id, auth.uid()) AS id)
  SELECT s.id AS session_id,
    (SELECT COUNT(*) FROM zane_session_entries e WHERE e.session_id = s.id)::int AS exercise_count,
    (SELECT COUNT(*) FROM zane_sets st WHERE st.session_id = s.id
       AND NOT st.warmup AND NOT st.skipped
       AND st.kg IS NOT NULL
       AND (st.reps IS NOT NULL OR st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL))::int AS done_sets,
    COALESCE((SELECT SUM(st.kg * COALESCE(
        CASE WHEN st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL
             THEN LEAST(COALESCE(st.reps_l, st.reps_r), COALESCE(st.reps_r, st.reps_l))
             ELSE st.reps END, 0))
      FROM zane_sets st WHERE st.session_id = s.id
        AND NOT st.warmup AND NOT st.skipped
        AND st.kg IS NOT NULL
        AND (st.reps IS NOT NULL OR st.reps_l IS NOT NULL OR st.reps_r IS NOT NULL)
    ), 0)::float AS volume
  FROM zane_sessions s
  WHERE s.user_id = (SELECT id FROM uid)
    AND s.ended IS NOT NULL;
$function$;

-- ── Trigger: create user_settings row on signup ────────────────────────────────

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ── Realtime ───────────────────────────────────────────────────────────────────
-- Coaching invites + messages are live; sessions are intentionally NOT published
-- (the local store owns the active session; coaches poll get_active_session_detail).

ALTER PUBLICATION supabase_realtime ADD TABLE zane_coaching;
ALTER PUBLICATION supabase_realtime ADD TABLE zane_coaching_notes;
