-- Reconciliation baseline for the schema that was historically installed in
-- the SQL editor before it was put in supabase_migrations.schema_migrations.
--
-- This migration is deliberately before the first recorded production
-- migration.  It contains only the pre-2026-05-29 foundation; later changes
-- stay in their original order and are replayed below it.  Every statement is
-- idempotent because Supabase can rebase a branch whose database already has
-- part of the old, untracked schema.

CREATE TABLE IF NOT EXISTS public.zane_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.zane_exercises (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  tags text[] NOT NULL DEFAULT '{}',
  note text NOT NULL DEFAULT '',
  category text,
  unilateral boolean NOT NULL DEFAULT false,
  equipment text,
  progression_reps integer
);

CREATE TABLE IF NOT EXISTS public.zane_schedules (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  days jsonb NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS public.zane_sessions (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  schedule_id text,
  day_id text,
  day_name text,
  date timestamptz,
  started_at timestamptz,
  ended timestamptz,
  entries jsonb NOT NULL DEFAULT '[]',
  duration_minutes integer
);

CREATE TABLE IF NOT EXISTS public.zane_user_settings (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  active_schedule_id text,
  cycle_index integer NOT NULL DEFAULT 0,
  cycle_start_date text,
  last_advanced_date date,
  week_plan_start_date date,
  in_progress_session_id text,
  unit text NOT NULL DEFAULT 'kg',
  rest_default integer NOT NULL DEFAULT 120,
  rest_big integer DEFAULT 180,
  rest_medium integer DEFAULT 120,
  rest_small integer DEFAULT 90,
  push_enabled boolean DEFAULT false,
  pushover_user_key text,
  cycle_week_view boolean DEFAULT false,
  accent_color text DEFAULT 'gold',
  dark_mode text DEFAULT 'dark',
  tempo_enabled boolean DEFAULT false,
  tempo_eccentric numeric DEFAULT 4,
  tempo_concentric numeric DEFAULT 1,
  smart_progression boolean DEFAULT false,
  progression_range_top integer DEFAULT 4,
  equipment_config jsonb,
  custom_day_types text[] NOT NULL DEFAULT '{}',
  reminder_enabled boolean NOT NULL DEFAULT false,
  reminder_time text NOT NULL DEFAULT '07:00',
  next_reminder_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.zane_pushover_active (
  id text PRIMARY KEY DEFAULT 'singleton',
  nonce text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.zane_feature_grants (
  feature text NOT NULL,
  email text NOT NULL,
  PRIMARY KEY (feature, email)
);

CREATE TABLE IF NOT EXISTS public.zane_skips (
  id text PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  date text NOT NULL,
  day_id text,
  day_name text,
  skip_reason text,
  skipped_at timestamptz DEFAULT now()
);

-- These two device-event tables predate the first recorded retention job.  A
-- later migration schedules the cleanup; keeping the tables here makes that
-- first migration replayable on a clean branch without copying any data.
CREATE TABLE IF NOT EXISTS public.motion_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id integer NOT NULL,
  sensor_name text NOT NULL,
  room text NOT NULL,
  presence boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.door_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  door_name text NOT NULL,
  state text NOT NULL CHECK (state IN ('open', 'closed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.zane_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_feature_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zane_skips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motion_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.door_events ENABLE ROW LEVEL SECURITY;

DO $policy$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_profiles' AND policyname = 'own profile') THEN
    CREATE POLICY "own profile" ON public.zane_profiles FOR ALL USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_exercises' AND policyname = 'own exercises') THEN
    CREATE POLICY "own exercises" ON public.zane_exercises FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_schedules' AND policyname = 'own schedules') THEN
    CREATE POLICY "own schedules" ON public.zane_schedules FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_sessions' AND policyname = 'own sessions') THEN
    CREATE POLICY "own sessions" ON public.zane_sessions FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_user_settings' AND policyname = 'own settings') THEN
    CREATE POLICY "own settings" ON public.zane_user_settings FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_feature_grants' AND policyname = 'read feature grants') THEN
    CREATE POLICY "read feature grants" ON public.zane_feature_grants FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'zane_skips' AND policyname = 'own skips') THEN
    CREATE POLICY "own skips" ON public.zane_skips FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END
$policy$;

-- The event tables are deliberately RLS-enabled without client policies:
-- device ingestion is service-role-only.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  INSERT INTO public.zane_user_settings (user_id) VALUES (NEW.id)
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

DO $publication$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (
       SELECT 1 FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'zane_sessions'
     ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.zane_sessions;
  END IF;
END
$publication$;
