/* ─── System Exercise Library (read-only "Exercise DB") ──────────────────────
   An original, curated catalogue of strength/hypertrophy movements — staples
   plus deeper cuts (Olympic lifts, powerlifting variations, calisthenics,
   grip & specialty work) — in the app's own exercise shape. Ships as a static
   bundle (no per-user DB rows): plans/sessions may reference a `sys_…` id
   directly (read-only), and the user can DUPLICATE any entry into their own
   `zane_exercises` to customise it.

   NOT wired into the app yet — this is the data layer only. The Library
   "Exercise DB" tab, the id→exercise lookup merge, and the Duplicate flow come
   in a follow-up.

   Entry shape (compact — defaults keep the file small):
     { id, name, tags: [muscle…], equipment, movement, logMode }
   Defaults when a field is omitted:
     movement → 'bilateral'   |   logMode → 'weight'   |   category → null
   logMode (see LB.exerciseLogMode): 'checkbox' (tick only) | 'reps' (reps, no
     weight) | 'weight' (weight + reps). Omit for normal weighted lifts.
   Vocabularies must match the app:
     tags      → Abs Back Biceps Calves Chest Forearms Glutes Hamstrings Quads Shoulders Triceps
     equipment → no_equipment bodyweight cable dumbbell barbell_dual machine barbell_single
     movement  → bilateral | unilateral | mobility
   Notes on tag mapping: the app has no trap/shin/adductor tag, so traps map to
   Back and tibialis work maps to Calves. Kettlebell movements use the closest
   loadable bucket (dumbbell); sleds/bands/pinch use no_equipment. Primary mover
   is listed first; multi-tag compounds count toward each tagged muscle in the
   sets-per-muscle view. Retag after duplicating to taste. */
window.SYSTEM_EXERCISES = [
  // ── Chest ──────────────────────────────────────────────────────────────────
  { id: 'sys_barbell_bench_press',   name: 'Barbell Bench Press',          tags: ['Chest','Triceps','Shoulders'], equipment: 'barbell_dual' },
  { id: 'sys_incline_barbell_bench', name: 'Incline Barbell Bench Press',  tags: ['Chest','Shoulders','Triceps'], equipment: 'barbell_dual' },
  { id: 'sys_decline_barbell_bench', name: 'Decline Barbell Bench Press',  tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_wide_grip_bench',       name: 'Wide-Grip Bench Press',        tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_reverse_grip_bench',    name: 'Reverse-Grip Bench Press',     tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_floor_press',           name: 'Floor Press',                  tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_spoto_press',           name: 'Spoto Press',                  tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_larsen_press',          name: 'Larsen Press',                 tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_guillotine_press',      name: 'Guillotine Press',             tags: ['Chest'],                       equipment: 'barbell_dual' },
  { id: 'sys_board_press',           name: 'Board Press',                  tags: ['Chest','Triceps'],             equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_bench_press',  name: 'Dumbbell Bench Press',         tags: ['Chest','Triceps','Shoulders'], equipment: 'dumbbell' },
  { id: 'sys_incline_dumbbell_press',name: 'Incline Dumbbell Press',       tags: ['Chest','Shoulders','Triceps'], equipment: 'dumbbell' },
  { id: 'sys_decline_dumbbell_press',name: 'Decline Dumbbell Press',       tags: ['Chest','Triceps'],             equipment: 'dumbbell' },
  { id: 'sys_dumbbell_floor_press',  name: 'Dumbbell Floor Press',         tags: ['Chest','Triceps'],             equipment: 'dumbbell' },
  { id: 'sys_squeeze_press',         name: 'Dumbbell Squeeze Press',       tags: ['Chest','Triceps'],             equipment: 'dumbbell' },
  { id: 'sys_machine_chest_press',   name: 'Machine Chest Press',          tags: ['Chest','Triceps'],             equipment: 'machine' },
  { id: 'sys_incline_machine_press', name: 'Incline Machine Press',        tags: ['Chest','Shoulders','Triceps'], equipment: 'machine' },
  { id: 'sys_smith_bench_press',     name: 'Smith Machine Bench Press',    tags: ['Chest','Triceps'],             equipment: 'machine' },
  { id: 'sys_cable_bench_press',     name: 'Cable Bench Press',            tags: ['Chest','Triceps'],             equipment: 'cable' },
  { id: 'sys_landmine_chest_press',  name: 'Landmine Chest Press',         tags: ['Chest','Shoulders'],           equipment: 'barbell_single', movement: 'unilateral' },
  { id: 'sys_dumbbell_fly',          name: 'Dumbbell Fly',                 tags: ['Chest'],                       equipment: 'dumbbell' },
  { id: 'sys_incline_dumbbell_fly',  name: 'Incline Dumbbell Fly',         tags: ['Chest'],                       equipment: 'dumbbell' },
  { id: 'sys_cable_fly',             name: 'Cable Fly',                    tags: ['Chest'],                       equipment: 'cable' },
  { id: 'sys_low_high_cable_fly',    name: 'Low-to-High Cable Fly',        tags: ['Chest'],                       equipment: 'cable' },
  { id: 'sys_high_low_cable_fly',    name: 'High-to-Low Cable Fly',        tags: ['Chest'],                       equipment: 'cable' },
  { id: 'sys_single_arm_cable_fly',  name: 'Single-Arm Cable Fly',         tags: ['Chest'],                       equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_pec_deck',              name: 'Pec Deck',                     tags: ['Chest'],                       equipment: 'machine' },
  { id: 'sys_svend_press',           name: 'Svend Press',                  tags: ['Chest'],                       equipment: 'no_equipment' },
  { id: 'sys_chest_dip',             name: 'Chest Dip',                    tags: ['Chest','Triceps'],             equipment: 'bodyweight' },
  { id: 'sys_push_up',               name: 'Push-Up',                      tags: ['Chest','Triceps','Shoulders'], equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_deficit_push_up',       name: 'Deficit Push-Up',              tags: ['Chest','Triceps'],             equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_archer_push_up',        name: 'Archer Push-Up',               tags: ['Chest','Triceps'],             equipment: 'bodyweight', movement: 'unilateral', logMode: 'reps' },
  { id: 'sys_ring_push_up',          name: 'Ring Push-Up',                 tags: ['Chest','Triceps'],             equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_plyo_push_up',          name: 'Plyometric Push-Up',           tags: ['Chest','Triceps'],             equipment: 'bodyweight', logMode: 'reps' },

  // ── Back (lats, mid-back, traps, lower back) ─────────────────────────────────
  { id: 'sys_deadlift',              name: 'Deadlift',                     tags: ['Back','Glutes','Hamstrings'],  equipment: 'barbell_dual' },
  { id: 'sys_sumo_deadlift',         name: 'Sumo Deadlift',                tags: ['Back','Glutes','Quads'],       equipment: 'barbell_dual' },
  { id: 'sys_trap_bar_deadlift',     name: 'Trap Bar Deadlift',            tags: ['Back','Quads','Glutes'],       equipment: 'barbell_dual' },
  { id: 'sys_deficit_deadlift',      name: 'Deficit Deadlift',             tags: ['Back','Glutes','Hamstrings'],  equipment: 'barbell_dual' },
  { id: 'sys_snatch_grip_deadlift',  name: 'Snatch-Grip Deadlift',         tags: ['Back','Hamstrings','Glutes'],  equipment: 'barbell_dual' },
  { id: 'sys_rack_pull',             name: 'Rack Pull',                    tags: ['Back','Glutes'],               equipment: 'barbell_dual' },
  { id: 'sys_barbell_row',           name: 'Barbell Row',                  tags: ['Back','Biceps'],               equipment: 'barbell_dual' },
  { id: 'sys_pendlay_row',           name: 'Pendlay Row',                  tags: ['Back','Biceps'],               equipment: 'barbell_dual' },
  { id: 'sys_yates_row',             name: 'Yates Row',                    tags: ['Back','Biceps'],               equipment: 'barbell_dual' },
  { id: 'sys_seal_row',              name: 'Seal Row',                     tags: ['Back','Biceps'],               equipment: 'barbell_dual' },
  { id: 'sys_reverse_grip_row',      name: 'Reverse-Grip Barbell Row',     tags: ['Back','Biceps'],               equipment: 'barbell_dual' },
  { id: 'sys_t_bar_row',             name: 'T-Bar Row',                    tags: ['Back','Biceps'],               equipment: 'barbell_single' },
  { id: 'sys_landmine_row',          name: 'Landmine Row',                 tags: ['Back','Biceps'],               equipment: 'barbell_single' },
  { id: 'sys_meadows_row',           name: 'Meadows Row',                  tags: ['Back','Biceps'],               equipment: 'barbell_single', movement: 'unilateral' },
  { id: 'sys_dumbbell_row',          name: 'Single-Arm Dumbbell Row',      tags: ['Back','Biceps'],               equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_kroc_row',              name: 'Kroc Row',                     tags: ['Back','Biceps'],               equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_chest_supported_row',   name: 'Chest-Supported Dumbbell Row', tags: ['Back','Biceps'],               equipment: 'dumbbell' },
  { id: 'sys_gorilla_row',           name: 'Gorilla Row',                  tags: ['Back','Biceps'],               equipment: 'dumbbell' },
  { id: 'sys_renegade_row',          name: 'Renegade Row',                 tags: ['Back','Abs'],                  equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_seated_cable_row',      name: 'Seated Cable Row',             tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_wide_grip_cable_row',   name: 'Wide-Grip Cable Row',          tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_single_arm_cable_row',  name: 'Single-Arm Cable Row',         tags: ['Back','Biceps'],               equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_machine_row',           name: 'Machine Row',                  tags: ['Back','Biceps'],               equipment: 'machine' },
  { id: 'sys_machine_high_row',      name: 'Machine High Row',             tags: ['Back','Biceps'],               equipment: 'machine' },
  { id: 'sys_lat_pulldown',          name: 'Lat Pulldown',                 tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_wide_grip_pulldown',    name: 'Wide-Grip Lat Pulldown',       tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_close_grip_pulldown',   name: 'Close-Grip Lat Pulldown',      tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_neutral_grip_pulldown', name: 'Neutral-Grip Lat Pulldown',    tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_single_arm_pulldown',   name: 'Single-Arm Lat Pulldown',      tags: ['Back','Biceps'],               equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_behind_neck_pulldown',  name: 'Behind-the-Neck Pulldown',     tags: ['Back','Biceps'],               equipment: 'cable' },
  { id: 'sys_straight_arm_pulldown', name: 'Straight-Arm Pulldown',        tags: ['Back'],                        equipment: 'cable' },
  { id: 'sys_cable_pullover',        name: 'Cable Pullover',               tags: ['Back','Chest'],                equipment: 'cable' },
  { id: 'sys_machine_pullover',      name: 'Machine Pullover',             tags: ['Back','Chest'],                equipment: 'machine' },
  { id: 'sys_dumbbell_pullover',     name: 'Dumbbell Pullover',            tags: ['Back','Chest'],                equipment: 'dumbbell' },
  { id: 'sys_pull_up',               name: 'Pull-Up',                      tags: ['Back','Biceps'],               equipment: 'bodyweight' },
  { id: 'sys_weighted_pull_up',      name: 'Weighted Pull-Up',             tags: ['Back','Biceps'],               equipment: 'bodyweight' },
  { id: 'sys_chin_up',               name: 'Chin-Up',                      tags: ['Back','Biceps'],               equipment: 'bodyweight' },
  { id: 'sys_neutral_grip_pull_up',  name: 'Neutral-Grip Pull-Up',         tags: ['Back','Biceps'],               equipment: 'bodyweight' },
  { id: 'sys_archer_pull_up',        name: 'Archer Pull-Up',               tags: ['Back','Biceps'],               equipment: 'bodyweight', movement: 'unilateral' },
  { id: 'sys_commando_pull_up',      name: 'Commando Pull-Up',             tags: ['Back','Biceps'],               equipment: 'bodyweight' },
  { id: 'sys_muscle_up',             name: 'Muscle-Up',                    tags: ['Back','Chest','Triceps'],      equipment: 'bodyweight' },
  { id: 'sys_inverted_row',          name: 'Inverted Row',                 tags: ['Back','Biceps'],               equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_assisted_pull_up',      name: 'Assisted Pull-Up',             tags: ['Back','Biceps'],               equipment: 'machine' },
  { id: 'sys_back_extension',        name: 'Back Extension',               tags: ['Back','Glutes','Hamstrings'],  equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_reverse_hyper',         name: 'Reverse Hyperextension',       tags: ['Back','Glutes','Hamstrings'],  equipment: 'machine' },
  { id: 'sys_superman',              name: 'Superman',                     tags: ['Back'],                        equipment: 'bodyweight', logMode: 'reps' },
  // traps
  { id: 'sys_barbell_shrug',         name: 'Barbell Shrug',                tags: ['Back'],                        equipment: 'barbell_dual' },
  { id: 'sys_behind_back_shrug',     name: 'Behind-the-Back Shrug',        tags: ['Back'],                        equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_shrug',        name: 'Dumbbell Shrug',               tags: ['Back'],                        equipment: 'dumbbell' },
  { id: 'sys_cable_shrug',           name: 'Cable Shrug',                  tags: ['Back'],                        equipment: 'cable' },
  { id: 'sys_trap_bar_shrug',        name: 'Trap Bar Shrug',               tags: ['Back'],                        equipment: 'barbell_dual' },
  { id: 'sys_power_shrug',           name: 'Power Shrug',                  tags: ['Back'],                        equipment: 'barbell_dual' },

  // ── Shoulders (delts) ────────────────────────────────────────────────────────
  { id: 'sys_overhead_press',        name: 'Overhead Press',               tags: ['Shoulders','Triceps'],         equipment: 'barbell_dual' },
  { id: 'sys_seated_barbell_ohp',    name: 'Seated Barbell Overhead Press',tags: ['Shoulders','Triceps'],         equipment: 'barbell_dual' },
  { id: 'sys_push_press',            name: 'Push Press',                   tags: ['Shoulders','Triceps'],         equipment: 'barbell_dual' },
  { id: 'sys_behind_neck_press',     name: 'Behind-the-Neck Press',        tags: ['Shoulders','Triceps'],         equipment: 'barbell_dual' },
  { id: 'sys_z_press',               name: 'Z Press',                      tags: ['Shoulders','Triceps'],         equipment: 'barbell_dual' },
  { id: 'sys_bradford_press',        name: 'Bradford Press',               tags: ['Shoulders','Triceps'],         equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_shoulder_press',name: 'Dumbbell Shoulder Press',     tags: ['Shoulders','Triceps'],         equipment: 'dumbbell' },
  { id: 'sys_arnold_press',          name: 'Arnold Press',                 tags: ['Shoulders','Triceps'],         equipment: 'dumbbell' },
  { id: 'sys_cuban_press',           name: 'Cuban Press',                  tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_kettlebell_ohp',        name: 'Kettlebell Overhead Press',    tags: ['Shoulders','Triceps'],         equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_machine_shoulder_press',name: 'Machine Shoulder Press',       tags: ['Shoulders','Triceps'],         equipment: 'machine' },
  { id: 'sys_viking_press',          name: 'Viking Press',                 tags: ['Shoulders','Triceps'],         equipment: 'machine' },
  { id: 'sys_landmine_press',        name: 'Landmine Press',               tags: ['Shoulders','Triceps'],         equipment: 'barbell_single', movement: 'unilateral' },
  { id: 'sys_dumbbell_lateral_raise',name: 'Dumbbell Lateral Raise',       tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_seated_lateral_raise',  name: 'Seated Dumbbell Lateral Raise',tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_cable_lateral_raise',   name: 'Cable Lateral Raise',          tags: ['Shoulders'],                   equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_leaning_cable_lateral', name: 'Leaning Cable Lateral Raise',  tags: ['Shoulders'],                   equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_machine_lateral_raise', name: 'Machine Lateral Raise',        tags: ['Shoulders'],                   equipment: 'machine' },
  { id: 'sys_lu_raise',              name: 'Lu Raise',                     tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_dumbbell_front_raise',  name: 'Dumbbell Front Raise',         tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_plate_front_raise',     name: 'Plate Front Raise',            tags: ['Shoulders'],                   equipment: 'no_equipment' },
  { id: 'sys_cable_front_raise',     name: 'Cable Front Raise',            tags: ['Shoulders'],                   equipment: 'cable' },
  { id: 'sys_y_raise',               name: 'Y-Raise',                      tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_dumbbell_rear_delt_fly',name: 'Dumbbell Rear Delt Fly',       tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_prone_rear_delt_raise', name: 'Prone Incline Rear Delt Raise',tags: ['Shoulders'],                   equipment: 'dumbbell' },
  { id: 'sys_reverse_pec_deck',      name: 'Reverse Pec Deck',             tags: ['Shoulders'],                   equipment: 'machine' },
  { id: 'sys_cable_rear_delt_fly',   name: 'Cable Rear Delt Fly',          tags: ['Shoulders'],                   equipment: 'cable' },
  { id: 'sys_face_pull',             name: 'Face Pull',                    tags: ['Shoulders','Back'],            equipment: 'cable' },
  { id: 'sys_band_pull_apart',       name: 'Band Pull-Apart',              tags: ['Shoulders','Back'],            equipment: 'no_equipment', logMode: 'reps' },
  { id: 'sys_barbell_upright_row',   name: 'Barbell Upright Row',          tags: ['Shoulders','Back'],            equipment: 'barbell_dual' },
  { id: 'sys_cable_upright_row',     name: 'Cable Upright Row',            tags: ['Shoulders','Back'],            equipment: 'cable' },

  // ── Biceps ───────────────────────────────────────────────────────────────────
  { id: 'sys_barbell_curl',          name: 'Barbell Curl',                 tags: ['Biceps'],                      equipment: 'barbell_dual' },
  { id: 'sys_ez_bar_curl',           name: 'EZ-Bar Curl',                  tags: ['Biceps'],                      equipment: 'barbell_dual' },
  { id: 'sys_wide_grip_curl',        name: 'Wide-Grip Barbell Curl',       tags: ['Biceps'],                      equipment: 'barbell_dual' },
  { id: 'sys_drag_curl',             name: 'Drag Curl',                    tags: ['Biceps'],                      equipment: 'barbell_dual' },
  { id: 'sys_twenty_ones',           name: '21s Barbell Curl',             tags: ['Biceps'],                      equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_curl',         name: 'Dumbbell Curl',                tags: ['Biceps'],                      equipment: 'dumbbell' },
  { id: 'sys_alternating_curl',      name: 'Alternating Dumbbell Curl',    tags: ['Biceps'],                      equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_incline_dumbbell_curl', name: 'Incline Dumbbell Curl',        tags: ['Biceps'],                      equipment: 'dumbbell' },
  { id: 'sys_hammer_curl',           name: 'Hammer Curl',                  tags: ['Biceps','Forearms'],           equipment: 'dumbbell' },
  { id: 'sys_cross_body_hammer',     name: 'Cross-Body Hammer Curl',       tags: ['Biceps','Forearms'],           equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_zottman_curl',          name: 'Zottman Curl',                 tags: ['Biceps','Forearms'],           equipment: 'dumbbell' },
  { id: 'sys_waiter_curl',           name: 'Waiter Curl',                  tags: ['Biceps'],                      equipment: 'dumbbell' },
  { id: 'sys_concentration_curl',    name: 'Concentration Curl',           tags: ['Biceps'],                      equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_spider_curl',           name: 'Spider Curl',                  tags: ['Biceps'],                      equipment: 'dumbbell' },
  { id: 'sys_preacher_curl',         name: 'Preacher Curl',                tags: ['Biceps'],                      equipment: 'barbell_dual' },
  { id: 'sys_machine_preacher_curl', name: 'Machine Preacher Curl',        tags: ['Biceps'],                      equipment: 'machine' },
  { id: 'sys_machine_curl',          name: 'Machine Biceps Curl',          tags: ['Biceps'],                      equipment: 'machine' },
  { id: 'sys_cable_curl',            name: 'Cable Curl',                   tags: ['Biceps'],                      equipment: 'cable' },
  { id: 'sys_bayesian_cable_curl',   name: 'Bayesian Cable Curl',          tags: ['Biceps'],                      equipment: 'cable' },
  { id: 'sys_high_cable_curl',       name: 'High Cable Curl',              tags: ['Biceps'],                      equipment: 'cable' },
  { id: 'sys_rope_hammer_curl',      name: 'Cable Rope Hammer Curl',       tags: ['Biceps','Forearms'],           equipment: 'cable' },

  // ── Triceps ──────────────────────────────────────────────────────────────────
  { id: 'sys_close_grip_bench',      name: 'Close-Grip Bench Press',       tags: ['Triceps','Chest'],             equipment: 'barbell_dual' },
  { id: 'sys_jm_press',              name: 'JM Press',                     tags: ['Triceps'],                     equipment: 'barbell_dual' },
  { id: 'sys_california_press',      name: 'California Press',              tags: ['Triceps','Chest'],             equipment: 'barbell_dual' },
  { id: 'sys_skull_crusher',         name: 'Skull Crusher',                tags: ['Triceps'],                     equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_skull_crusher',name: 'Dumbbell Skull Crusher',       tags: ['Triceps'],                     equipment: 'dumbbell' },
  { id: 'sys_tate_press',            name: 'Tate Press',                   tags: ['Triceps'],                     equipment: 'dumbbell' },
  { id: 'sys_rolling_extension',     name: 'Rolling Triceps Extension',    tags: ['Triceps'],                     equipment: 'dumbbell' },
  { id: 'sys_overhead_db_ext',       name: 'Overhead Dumbbell Extension',  tags: ['Triceps'],                     equipment: 'dumbbell' },
  { id: 'sys_overhead_cable_ext',    name: 'Overhead Cable Extension',     tags: ['Triceps'],                     equipment: 'cable' },
  { id: 'sys_triceps_pushdown_rope', name: 'Rope Triceps Pushdown',        tags: ['Triceps'],                     equipment: 'cable' },
  { id: 'sys_triceps_pushdown_bar',  name: 'Bar Triceps Pushdown',         tags: ['Triceps'],                     equipment: 'cable' },
  { id: 'sys_reverse_grip_pushdown', name: 'Reverse-Grip Pushdown',        tags: ['Triceps'],                     equipment: 'cable' },
  { id: 'sys_single_arm_pushdown',   name: 'Single-Arm Cable Pushdown',    tags: ['Triceps'],                     equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_cross_cable_extension', name: 'Cross-Body Cable Extension',   tags: ['Triceps'],                     equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_dumbbell_kickback',     name: 'Dumbbell Kickback',            tags: ['Triceps'],                     equipment: 'dumbbell' },
  { id: 'sys_cable_kickback',        name: 'Cable Kickback',               tags: ['Triceps'],                     equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_triceps_dip',           name: 'Triceps Dip',                  tags: ['Triceps','Chest'],             equipment: 'bodyweight' },
  { id: 'sys_ring_dip',              name: 'Ring Dip',                     tags: ['Triceps','Chest'],             equipment: 'bodyweight' },
  { id: 'sys_bench_dip',             name: 'Bench Dip',                    tags: ['Triceps'],                     equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_diamond_push_up',       name: 'Diamond Push-Up',              tags: ['Triceps','Chest'],             equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_machine_dip',           name: 'Machine Dip',                  tags: ['Triceps','Chest'],             equipment: 'machine' },
  { id: 'sys_machine_triceps_ext',   name: 'Machine Triceps Extension',    tags: ['Triceps'],                     equipment: 'machine' },

  // ── Forearms / grip ──────────────────────────────────────────────────────────
  { id: 'sys_barbell_wrist_curl',    name: 'Barbell Wrist Curl',           tags: ['Forearms'],                    equipment: 'barbell_dual' },
  { id: 'sys_reverse_wrist_curl',    name: 'Barbell Reverse Wrist Curl',   tags: ['Forearms'],                    equipment: 'barbell_dual' },
  { id: 'sys_behind_back_wrist_curl',name: 'Behind-the-Back Wrist Curl',   tags: ['Forearms'],                    equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_wrist_curl',   name: 'Dumbbell Wrist Curl',          tags: ['Forearms'],                    equipment: 'dumbbell' },
  { id: 'sys_reverse_curl',          name: 'Reverse Curl',                 tags: ['Forearms','Biceps'],           equipment: 'barbell_dual' },
  { id: 'sys_cable_reverse_curl',    name: 'Cable Reverse Curl',           tags: ['Forearms','Biceps'],           equipment: 'cable' },
  { id: 'sys_wrist_roller',          name: 'Wrist Roller',                 tags: ['Forearms'],                    equipment: 'no_equipment', logMode: 'reps' },
  { id: 'sys_plate_pinch',           name: 'Plate Pinch Hold',             tags: ['Forearms'],                    equipment: 'no_equipment' },
  { id: 'sys_dead_hang',             name: 'Dead Hang',                    tags: ['Forearms','Back'],             equipment: 'bodyweight', logMode: 'checkbox' },
  { id: 'sys_farmers_carry',         name: "Farmer's Carry",               tags: ['Forearms','Back'],             equipment: 'dumbbell' },
  { id: 'sys_wrist_extension',       name: 'Dumbbell Wrist Extension',     tags: ['Forearms'],                    equipment: 'dumbbell' },

  // ── Quads ────────────────────────────────────────────────────────────────────
  { id: 'sys_back_squat',            name: 'Back Squat',                   tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_high_bar_squat',        name: 'High-Bar Squat',               tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_low_bar_squat',         name: 'Low-Bar Squat',                tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_front_squat',           name: 'Front Squat',                  tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_paused_squat',          name: 'Paused Squat',                 tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_box_squat',             name: 'Box Squat',                    tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_safety_bar_squat',      name: 'Safety Bar Squat',             tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_zercher_squat',         name: 'Zercher Squat',                tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_overhead_squat',        name: 'Overhead Squat',               tags: ['Quads','Shoulders'],           equipment: 'barbell_dual' },
  { id: 'sys_anderson_squat',        name: 'Anderson Squat',               tags: ['Quads','Glutes'],              equipment: 'barbell_dual' },
  { id: 'sys_landmine_squat',        name: 'Landmine Squat',               tags: ['Quads','Glutes'],              equipment: 'barbell_single' },
  { id: 'sys_hack_squat',            name: 'Hack Squat',                   tags: ['Quads','Glutes'],              equipment: 'machine' },
  { id: 'sys_pendulum_squat',        name: 'Pendulum Squat',               tags: ['Quads','Glutes'],              equipment: 'machine' },
  { id: 'sys_belt_squat',            name: 'Belt Squat',                   tags: ['Quads','Glutes'],              equipment: 'machine' },
  { id: 'sys_hatfield_squat',        name: 'Hatfield Squat',               tags: ['Quads','Glutes'],              equipment: 'machine' },
  { id: 'sys_smith_squat',           name: 'Smith Machine Squat',          tags: ['Quads','Glutes'],              equipment: 'machine' },
  { id: 'sys_leg_press',             name: 'Leg Press',                    tags: ['Quads','Glutes'],              equipment: 'machine' },
  { id: 'sys_single_leg_press',      name: 'Single-Leg Press',             tags: ['Quads','Glutes'],              equipment: 'machine', movement: 'unilateral' },
  { id: 'sys_leg_extension',         name: 'Leg Extension',                tags: ['Quads'],                       equipment: 'machine' },
  { id: 'sys_single_leg_extension',  name: 'Single-Leg Extension',         tags: ['Quads'],                       equipment: 'machine', movement: 'unilateral' },
  { id: 'sys_goblet_squat',          name: 'Goblet Squat',                 tags: ['Quads','Glutes'],              equipment: 'dumbbell' },
  { id: 'sys_cyclist_squat',         name: 'Heels-Elevated Goblet Squat',  tags: ['Quads'],                       equipment: 'dumbbell' },
  { id: 'sys_bulgarian_split_squat', name: 'Bulgarian Split Squat',        tags: ['Quads','Glutes'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_split_squat',           name: 'Dumbbell Split Squat',         tags: ['Quads','Glutes'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_walking_lunge',         name: 'Walking Lunge',                tags: ['Quads','Glutes'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_reverse_lunge',         name: 'Reverse Lunge',                tags: ['Quads','Glutes'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_lateral_lunge',         name: 'Lateral Lunge',                tags: ['Quads','Glutes'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_curtsy_lunge',          name: 'Curtsy Lunge',                 tags: ['Glutes','Quads'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_dumbbell_step_up',      name: 'Dumbbell Step-Up',             tags: ['Quads','Glutes'],              equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_sissy_squat',           name: 'Sissy Squat',                  tags: ['Quads'],                       equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_pistol_squat',          name: 'Pistol Squat',                 tags: ['Quads','Glutes'],              equipment: 'bodyweight', movement: 'unilateral' },
  { id: 'sys_cossack_squat',         name: 'Cossack Squat',                tags: ['Quads','Glutes'],              equipment: 'bodyweight', movement: 'unilateral' },
  { id: 'sys_wall_sit',              name: 'Wall Sit',                     tags: ['Quads'],                       equipment: 'bodyweight', logMode: 'checkbox' },

  // ── Hamstrings ───────────────────────────────────────────────────────────────
  { id: 'sys_romanian_deadlift',     name: 'Romanian Deadlift',            tags: ['Hamstrings','Glutes'],         equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_rdl',          name: 'Dumbbell Romanian Deadlift',   tags: ['Hamstrings','Glutes'],         equipment: 'dumbbell' },
  { id: 'sys_deficit_rdl',           name: 'Deficit Romanian Deadlift',    tags: ['Hamstrings','Glutes'],         equipment: 'barbell_dual' },
  { id: 'sys_stiff_leg_deadlift',    name: 'Stiff-Leg Deadlift',           tags: ['Hamstrings','Glutes'],         equipment: 'barbell_dual' },
  { id: 'sys_single_leg_rdl',        name: 'Single-Leg Romanian Deadlift', tags: ['Hamstrings','Glutes'],         equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_lying_leg_curl',        name: 'Lying Leg Curl',               tags: ['Hamstrings'],                  equipment: 'machine' },
  { id: 'sys_seated_leg_curl',       name: 'Seated Leg Curl',              tags: ['Hamstrings'],                  equipment: 'machine' },
  { id: 'sys_single_leg_curl',       name: 'Single-Leg Curl',              tags: ['Hamstrings'],                  equipment: 'machine', movement: 'unilateral' },
  { id: 'sys_nordic_curl',           name: 'Nordic Hamstring Curl',        tags: ['Hamstrings'],                  equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_razor_curl',            name: 'Razor Curl',                   tags: ['Hamstrings'],                  equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_slider_leg_curl',       name: 'Slider Leg Curl',              tags: ['Hamstrings'],                  equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_ghr',                   name: 'Glute-Ham Raise',              tags: ['Hamstrings','Glutes'],         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_good_morning',          name: 'Good Morning',                 tags: ['Hamstrings','Glutes','Back'],  equipment: 'barbell_dual' },
  { id: 'sys_cable_pull_through',    name: 'Cable Pull-Through',           tags: ['Glutes','Hamstrings'],         equipment: 'cable' },
  { id: 'sys_kettlebell_swing',      name: 'Kettlebell Swing',             tags: ['Glutes','Hamstrings'],         equipment: 'dumbbell' },

  // ── Glutes ───────────────────────────────────────────────────────────────────
  { id: 'sys_hip_thrust',            name: 'Barbell Hip Thrust',           tags: ['Glutes','Hamstrings'],         equipment: 'barbell_dual' },
  { id: 'sys_b_stance_hip_thrust',   name: 'B-Stance Hip Thrust',          tags: ['Glutes'],                      equipment: 'barbell_dual', movement: 'unilateral' },
  { id: 'sys_machine_hip_thrust',    name: 'Machine Hip Thrust',           tags: ['Glutes'],                      equipment: 'machine' },
  { id: 'sys_single_leg_hip_thrust', name: 'Single-Leg Hip Thrust',        tags: ['Glutes'],                      equipment: 'bodyweight', movement: 'unilateral', logMode: 'reps' },
  { id: 'sys_barbell_glute_bridge',  name: 'Barbell Glute Bridge',         tags: ['Glutes'],                      equipment: 'barbell_dual' },
  { id: 'sys_kas_glute_bridge',      name: 'Kas Glute Bridge',             tags: ['Glutes'],                      equipment: 'barbell_dual' },
  { id: 'sys_frog_pump',             name: 'Frog Pump',                    tags: ['Glutes'],                      equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_hip_abduction_machine', name: 'Hip Abduction Machine',        tags: ['Glutes'],                      equipment: 'machine' },
  { id: 'sys_cable_hip_abduction',   name: 'Cable Hip Abduction',          tags: ['Glutes'],                      equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_banded_hip_abduction',  name: 'Banded Hip Abduction',         tags: ['Glutes'],                      equipment: 'no_equipment', logMode: 'reps' },
  { id: 'sys_cable_glute_kickback',  name: 'Cable Glute Kickback',         tags: ['Glutes'],                      equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_machine_glute_kickback',name: 'Machine Glute Kickback',       tags: ['Glutes'],                      equipment: 'machine', movement: 'unilateral' },
  { id: 'sys_hip_extension_45',      name: '45-Degree Hip Extension',      tags: ['Glutes','Hamstrings'],         equipment: 'bodyweight', logMode: 'reps' },

  // ── Calves ───────────────────────────────────────────────────────────────────
  { id: 'sys_standing_calf_raise',   name: 'Standing Calf Raise',          tags: ['Calves'],                      equipment: 'machine' },
  { id: 'sys_seated_calf_raise',     name: 'Seated Calf Raise',            tags: ['Calves'],                      equipment: 'machine' },
  { id: 'sys_leg_press_calf_raise',  name: 'Leg Press Calf Raise',         tags: ['Calves'],                      equipment: 'machine' },
  { id: 'sys_donkey_calf_raise',     name: 'Donkey Calf Raise',            tags: ['Calves'],                      equipment: 'machine' },
  { id: 'sys_smith_calf_raise',      name: 'Smith Machine Calf Raise',     tags: ['Calves'],                      equipment: 'machine' },
  { id: 'sys_dumbbell_calf_raise',   name: 'Dumbbell Standing Calf Raise', tags: ['Calves'],                      equipment: 'dumbbell' },
  { id: 'sys_single_leg_calf_raise', name: 'Single-Leg Calf Raise',        tags: ['Calves'],                      equipment: 'bodyweight', movement: 'unilateral', logMode: 'reps' },
  { id: 'sys_tibialis_raise',        name: 'Tibialis Raise',               tags: ['Calves'],                      equipment: 'bodyweight', logMode: 'reps' },

  // ── Abs / core ───────────────────────────────────────────────────────────────
  { id: 'sys_hanging_leg_raise',     name: 'Hanging Leg Raise',            tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_hanging_knee_raise',    name: 'Hanging Knee Raise',           tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_toes_to_bar',           name: 'Toes-to-Bar',                  tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_windshield_wiper',      name: 'Hanging Windshield Wiper',     tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_cable_crunch',          name: 'Cable Crunch',                 tags: ['Abs'],                         equipment: 'cable' },
  { id: 'sys_machine_crunch',        name: 'Machine Crunch',               tags: ['Abs'],                         equipment: 'machine' },
  { id: 'sys_crunch',                name: 'Crunch',                       tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_sit_up',                name: 'Sit-Up',                       tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_decline_sit_up',        name: 'Decline Sit-Up',               tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_lying_leg_raise',       name: 'Lying Leg Raise',              tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_reverse_crunch',        name: 'Reverse Crunch',               tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_bicycle_crunch',        name: 'Bicycle Crunch',               tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_v_up',                  name: 'V-Up',                         tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_flutter_kicks',         name: 'Flutter Kicks',                tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_plank',                 name: 'Plank',                        tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'checkbox' },
  { id: 'sys_side_plank',            name: 'Side Plank',                   tags: ['Abs'],                         equipment: 'bodyweight', movement: 'unilateral', logMode: 'checkbox' },
  { id: 'sys_hollow_hold',           name: 'Hollow Body Hold',             tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'checkbox' },
  { id: 'sys_l_sit',                 name: 'L-Sit',                        tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'checkbox' },
  { id: 'sys_dragon_flag',           name: 'Dragon Flag',                  tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_ab_wheel_rollout',      name: 'Ab Wheel Rollout',             tags: ['Abs'],                         equipment: 'no_equipment', logMode: 'reps' },
  { id: 'sys_mountain_climber',      name: 'Mountain Climber',             tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_russian_twist',         name: 'Russian Twist',                tags: ['Abs'],                         equipment: 'bodyweight', logMode: 'reps' },
  { id: 'sys_pallof_press',          name: 'Pallof Press',                 tags: ['Abs'],                         equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_cable_woodchopper',     name: 'Cable Woodchopper',            tags: ['Abs'],                         equipment: 'cable', movement: 'unilateral' },
  { id: 'sys_landmine_twist',        name: 'Landmine Rotation',            tags: ['Abs'],                         equipment: 'barbell_single', movement: 'unilateral' },
  { id: 'sys_dumbbell_side_bend',    name: 'Dumbbell Side Bend',           tags: ['Abs'],                         equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_cable_side_bend',       name: 'Cable Side Bend',              tags: ['Abs'],                         equipment: 'cable', movement: 'unilateral' },

  // ── Olympic & full-body power ────────────────────────────────────────────────
  { id: 'sys_power_clean',           name: 'Power Clean',                  tags: ['Back','Quads','Shoulders'],    equipment: 'barbell_dual' },
  { id: 'sys_hang_clean',            name: 'Hang Clean',                   tags: ['Back','Quads','Shoulders'],    equipment: 'barbell_dual' },
  { id: 'sys_clean_and_jerk',        name: 'Clean and Jerk',               tags: ['Quads','Shoulders','Back'],    equipment: 'barbell_dual' },
  { id: 'sys_power_snatch',          name: 'Power Snatch',                 tags: ['Back','Quads','Shoulders'],    equipment: 'barbell_dual' },
  { id: 'sys_hang_snatch',           name: 'Hang Snatch',                  tags: ['Back','Quads','Shoulders'],    equipment: 'barbell_dual' },
  { id: 'sys_push_jerk',             name: 'Push Jerk',                    tags: ['Shoulders','Quads','Triceps'], equipment: 'barbell_dual' },
  { id: 'sys_thruster',              name: 'Thruster',                     tags: ['Quads','Shoulders'],           equipment: 'barbell_dual' },
  { id: 'sys_clean_and_press',       name: 'Clean and Press',              tags: ['Shoulders','Quads','Back'],    equipment: 'barbell_dual' },
  { id: 'sys_dumbbell_snatch',       name: 'Dumbbell Snatch',              tags: ['Shoulders','Back','Quads'],    equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_kettlebell_clean',      name: 'Kettlebell Clean',             tags: ['Back','Quads','Shoulders'],    equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_turkish_get_up',        name: 'Turkish Get-Up',               tags: ['Abs','Shoulders'],             equipment: 'dumbbell', movement: 'unilateral' },
  { id: 'sys_sled_push',             name: 'Sled Push',                    tags: ['Quads','Glutes'],              equipment: 'no_equipment' },
  { id: 'sys_sled_drag',             name: 'Sled Drag',                    tags: ['Quads','Hamstrings'],          equipment: 'no_equipment' },
];
